# Generated by Django 6.0.4 on 2026-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deliver_date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=1100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
